# Generated by Django 5.2.13 on 2026-05-02 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='hours',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
