# Generated by Django 5.2.13 on 2026-04-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_leavebalance_year_employeedocument'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='EmployeeDocument',
                ),
            ],
            database_operations=[],
        ),
    ]
