# Generated by Django 5.2.13 on 2026-04-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_employeedocument'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='leavebalance',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='leavebalance',
                    name='employee',
                ),
                migrations.RemoveField(
                    model_name='leaverequest',
                    name='employee',
                ),
                migrations.RemoveField(
                    model_name='leaverequest',
                    name='reviewed_by',
                ),
                migrations.DeleteModel(
                    name='LeaveAdjustmentLog',
                ),
                migrations.DeleteModel(
                    name='LeaveBalance',
                ),
                migrations.DeleteModel(
                    name='LeaveRequest',
                ),
            ],
            database_operations=[]
        ),
    ]
