# Generated by Django 5.2.13 on 2026-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_user_invite_sent_at_user_is_invited_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
