# Generated by Django 5.2.13 on 2026-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
