# Generated by Django 5.2.13 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
