# Generated by Django 5.2.13 on 2026-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_importjob_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
