# Generated by Django 5.2.13 on 2026-04-30 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_delete_employeedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='EmployeeDocument',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('work_permit', 'Work Permit'), ('other', 'Other')], max_length=20)),
                        ('label', models.CharField(blank=True, help_text="Optional human-readable label, e.g. 'Passport Renewal 2025'", max_length=120)),
                        ('file', models.FileField(upload_to='employee_docs/%Y/%m/')),
                        ('expiry_date', models.DateField(blank=True, null=True)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                        ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Employee Document',
                        'verbose_name_plural': 'Employee Documents',
                        'db_table': 'employees_employeedocument',
                        'ordering': ['-uploaded_at'],
                        'indexes': [models.Index(fields=['employee', 'doc_type'], name='employees_e_employe_41fbc8_idx'), models.Index(fields=['expiry_date'], name='employees_e_expiry__add9a8_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
