# Generated by Django 5.2.13 on 2026-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('work_permit', 'Work Permit'), ('ssic_gt', 'SSIC GT'), ('ssic_ht', 'SSIC HT'), ('security_bond', 'Security Bond'), ('other', 'Other')], max_length=20),
        ),
    ]
