# Generated by Django 5.2.13 on 2026-04-23 05:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=20)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation_ipa', models.CharField(blank=True, max_length=100, null=True)),
                ('ipa_salary', models.FloatField(blank=True, null=True)),
                ('per_hr', models.FloatField(blank=True, null=True)),
                ('designation_aug', models.CharField(blank=True, max_length=100, null=True)),
                ('work_permit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('ic_status', models.CharField(blank=True, max_length=50, null=True)),
                ('wp_expiry', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_issue_place', models.CharField(blank=True, max_length=100, null=True)),
                ('doa', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('ssic_gt_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('ssic_gt_exp', models.DateField(blank=True, null=True)),
                ('ssic_ht_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('ssic_ht_exp', models.DateField(blank=True, null=True)),
                ('work_at_height', models.BooleanField(default=False)),
                ('confined_space', models.BooleanField(default=False)),
                ('welder_no', models.CharField(blank=True, max_length=100, null=True)),
                ('lssc_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('signalman_rigger', models.BooleanField(default=False)),
                ('firewatchman', models.BooleanField(default=False)),
                ('gas_meter_carrier', models.BooleanField(default=False)),
                ('dynamac_pass_sn', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamac_pass_exp', models.DateField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=100, null=True)),
                ('pcp_status', models.CharField(blank=True, max_length=100, null=True)),
                ('security_bond_no', models.CharField(blank=True, max_length=100, null=True)),
                ('security_bond_exp', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.division')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
