# Generated by Django 5.2.13 on 2026-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_leaveadjustmentlog_leavebalance_leaverequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_joined_company'], name='employees_e_date_jo_3317bd_idx'),
        ),
    ]
