# Generated by Django 5.2.13 on 2026-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('client_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('work_order_no', models.CharField(max_length=100)),
                ('pr_no', models.CharField(max_length=100)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retention', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
