# Generated by Django 5.2.13 on 2026-04-30 06:23

import apps.leave.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_leavebalance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='LeaveRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('leave_type', models.CharField(choices=[('medical', 'Medical Leave'), ('casual', 'Casual Leave'), ('annual', 'Annual Leave'), ('unpaid', 'Unpaid Leave')], max_length=20)),
                        ('start_date', models.DateField()),
                        ('end_date', models.DateField()),
                        ('total_days', models.PositiveIntegerField()),
                        ('reason', models.TextField(blank=True, null=True)),
                        ('attachment', models.FileField(blank=True, help_text='Medical certificate or supporting document', null=True, upload_to='leave_attachments/%Y/%m/')),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                        ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                        ('rejection_reason', models.TextField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                        ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Leave Request',
                        'verbose_name_plural': 'Leave Requests',
                        'db_table': 'employees_leaverequest',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='LeaveAdjustmentLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('manual_add', 'Manual Balance Add'), ('manual_deduct', 'Manual Balance Deduct'), ('reset', 'Annual Reset')], max_length=20)),
                        ('note', models.TextField(blank=True, null=True)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_logs', to='employees.employee')),
                        ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='leave.leaverequest')),
                    ],
                    options={
                        'verbose_name': 'Leave Adjustment Log',
                        'verbose_name_plural': 'Leave Adjustment Logs',
                        'db_table': 'employees_leaveadjustmentlog',
                        'ordering': ['-timestamp'],
                    },
                ),
                migrations.CreateModel(
                    name='LeaveBalance',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('year', models.PositiveIntegerField(default=apps.leave.models.get_current_year)),
                        ('medical_entitled', models.IntegerField(default=14)),
                        ('casual_entitled', models.IntegerField(default=7)),
                        ('annual_entitled', models.IntegerField(default=14)),
                        ('medical_used', models.IntegerField(default=0)),
                        ('casual_used', models.IntegerField(default=0)),
                        ('annual_used', models.IntegerField(default=0)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                    ],
                    options={
                        'verbose_name': 'Leave Balance',
                        'verbose_name_plural': 'Leave Balances',
                        'db_table': 'employees_leavebalance',
                        'ordering': ['-year'],
                        'unique_together': {('employee', 'year')},
                    },
                ),
                migrations.AddIndex(
                    model_name='leaverequest',
                    index=models.Index(fields=['employee', 'status'], name='employees_l_employe_cc1aa4_idx'),
                ),
                migrations.AddIndex(
                    model_name='leaverequest',
                    index=models.Index(fields=['start_date', 'end_date'], name='employees_l_start_d_844d5d_idx'),
                ),
                migrations.AddIndex(
                    model_name='leaverequest',
                    index=models.Index(fields=['status', 'leave_type'], name='employees_l_status_47ffa2_idx'),
                ),
            ],
            database_operations=[]
        ),
    ]
